# Generated by Django 6.0.2 on 2026-07-23 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=150, verbose_name='Car Model / Name')),
                ('car_image', models.ImageField(upload_to='car_photos/', verbose_name='Car Image')),
                ('car_details', models.TextField(verbose_name='Car Specifications and Rental Details')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Contact Number for Calls')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='WhatsApp Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
